eureka:
  client:
    serviceUrl:
      defaultZone: http://saas-eureka-server:8761/eureka/ # 这个需要改为eureka-server
server:
  port: 8765
feign:
  hystrix:
    enabled: true
spring:
  application:
    name: service-feign
